
title: Matthew Burton Portfolio 

email: 36slices@gmail.com

description: >- # this means to ignore newlines until "baseurl:"
  A webpage designed to track my progress as a portfolio and store my journals/blog posts.
  "Kaizen: continuous improvement."

avatar: "/images/PortfolioImage1.jpg"

baseurl: "" # the subpath of your site, e.g. /blog

url: "" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  mattburt36

# Build settings
theme: minima

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
